title: hermanl0
description: Infrastructure, networking, and homelab writeups.
tagline: Infrastructure, networking, and homelab writeups.
url: "https://hermanl0.github.io"

remote_theme: jekyll/minima
markdown: kramdown

minima:
  skin: dark
  show_excerpts: true
