title: hermanl0
description: Infrastructure, networking, and homelab writeups.
tagline: Infrastructure, networking, and homelab writeups.
url: "https://hermanl0.github.io"

remote_theme: jekyll/minima
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto
  show_excerpts: true
  date_format: "%d %b %Y"
